{
    "author": "dj-22.5.2",
    "ua": "",
    "homeUrl": "https://www.31kan.vip/",
    //"dcVipFlag": "true",
    //"pCfgJs": "https://gimytv.com//static/js/playerconfig.js",
    //"pCfgJsR": "[\\W|\\S|.]*?MacPlayerConfig.player_list[\\W|\\S|.]*?=([\\W|\\S|.]*?),MacPlayerConfig.downer_list",
    //"dcShow2Vip": {},
    //"dcPlayUrl": "true",
    "cateManual": {
        "电影": "1",
        "电视剧": "2",
        "综艺": "3",
        "少儿": "33",
        "动漫": "4"

    },
    "homeVodNode": "//ul[contains(@class, 'myui-vodlist clearfix')]/li/div",
    "homeVodName": "/a[contains(@class, 'myui-vodlist__thumb')]/@title",
    "homeVodId": "/a[contains(@class, 'myui-vodlist__thumb')]/@href",
    "homeVodIdR": "/31kan/(\\S+).html",
    "homeVodImg": "/a[contains(@class, 'myui-vodlist__thumb')]/@data-original",
    "homeVodMark": "//span[contains(@class,'pic-text text-right')]/text()",

    // 分类页地址 {cateId} 分类id {catePg} 当前页
    "cateUrl": "https://www.31kan.vip/vodshow/{cateId}--------{catePg}---.html",
    "cateVodNode": "//ul[contains(@class, 'myui-vodlist clearfix')]/li/div",
    "cateVodName": "/a[contains(@class, 'myui-vodlist__thumb')]/@title",
    "cateVodId": "/a[contains(@class, 'myui-vodlist__thumb')]/@href",
    "cateVodIdR": "/31kan/(\\S+).html",
    "cateVodImg": "/a[contains(@class, 'myui-vodlist__thumb')]/@data-original",
    "cateVodMark": "//span[contains(@class,'pic-text text-right')]/text()",
    // 详情页地址 用于获取详情页信息 及 播放列表和地址
    "dtUrl": "https://www.31kan.vip/31kan/{vid}.html",

// 详情节点
    //"dtNode": "//div[contains(@class,'myui-content__thumb')]",
    //"dtName": "/a/@title",
    //"dtImg": "/a/img/@data-original",
    "dtNode": "//body",
    "dtName": "//div[@class='myui-content__thumb']/a/@title",
    "dtNameR": "",
    "dtImg": "//div[@class='myui-content__thumb']/a/img/@data-original",
    "dtImgR": "",

    "dtCate": "//div[@class='myui-content__detail']//span[contains(@class,'text-muted') and contains(text(), '分类')]/following-sibling::*/text()",
    "dtCateR": "",
    "dtYear": "//div[@class='myui-content__detail']//span[contains(@class,'text-muted') and contains(text(), '年份')]/following-sibling::*/text()",
    "dtYearR": "",
    "dtArea": "//div[@class='myui-content__detail']//span[contains(@class,'text-muted') and contains(text(), '地区')]/following-sibling::*/text()",
    "dtAreaR": "",
    "dtMark": "//div[@class='myui-content__detail']//span[contains(@class,'text-muted') and contains(text(), '更新')]/following-sibling::*/text()",
    "dtMarkR": "",
    "dtActor": "//div[@class='myui-content__detail']//span[contains(@class,'text-muted') and contains(text(), '主演')]/following-sibling::*/text()",
    "dtActorR": "",
    "dtDirector": "//div[@class='myui-content__detail']//span[contains(@class,'text-muted') and contains(text(), '导演')]/following-sibling::*/text()",
    "dtDirectorR": "",
    "dtDesc": "//div[@class='myui-content__detail']//span[contains(@class,'text-muted') and contains(text(), '简介')]/parent::text()",
    "dtDescR": "",

    "dtFromNode": "//div[contains(@class,'myui-panel_hd')]/div/ul[contains(@class,'nav nav-tabs active')]/li/a",
    "dtFromName": "/text()",
    "dtUrlNode": "//ul[contains(@class,'myui-content__list')]",
    "dtUrlSubNode": "/li/a",
    "dtUrlId": "@href",
    "dtUrlIdR": "/play/(\\S+).html",
    "dtUrlName": "/text()",
    "playUrl": "https://www.31kan.vip/play/{playUrl}.html",
    "searchUrl": "https://www.31kan.vip/index.php/ajax/suggest?mid=1&wd={wd}",
    "scVodNode": "json:list",
    "scVodName": "name",
    "scVodId": "id",
    "scVodIdR": "",
    "scVodImg": "pic",
    "scVodMark": ""
}
